a2_dct = {'AF': {'ee': 'Afganistan', 'en': 'Afghanistan'},
 'AX': {'ee': 'Ahvenamaa', 'en': 'Åland Islands'},
 'AL': {'ee': 'Albaania', 'en': 'Albania'},
 'DZ': {'ee': 'Alžeeria', 'en': 'Algeria'},
 'AS': {'ee': 'Ameerika Samoa', 'en': 'American Samoa'},
 'US': {'ee': 'Ameerika Ühendriigid', 'en': 'United States of America'},
 'AD': {'ee': 'Andorra', 'en': 'Andorra'},
 'AO': {'ee': 'Angola', 'en': 'Angola'},
 'AI': {'ee': 'Anguilla', 'en': 'Anguilla'},
 'AQ': {'ee': 'Antarktis', 'en': 'Antarctica'},
 'AG': {'ee': 'Antigua ja Barbuda', 'en': 'Antigua and Barbuda'},
 'AE': {'ee': 'Araabia Ühendemiraadid', 'en': 'United Arab Emirates'},
 'AR': {'ee': 'Argentina', 'en': 'Argentina'},
 'AM': {'ee': 'Armeenia', 'en': 'Armenia'},
 'AW': {'ee': 'Aruba', 'en': 'Aruba'},
 'AU': {'ee': 'Austraalia', 'en': 'Australia'},
 'AT': {'ee': 'Austria', 'en': 'Austria'},
 'AZ': {'ee': 'Aserbaidžaan', 'en': 'Azerbaijan'},
 'BS': {'ee': 'Bahama', 'en': 'Bahamas'},
 'BH': {'ee': 'Bahrein', 'en': 'Bahrain'},
 'BD': {'ee': 'Bangladesh', 'en': 'Bangladesh'},
 'BB': {'ee': 'Barbados', 'en': 'Barbados'},
 'PW': {'ee': 'Belau', 'en': 'Palau'},
 'BE': {'ee': 'Belgia', 'en': 'Belgium'},
 'BZ': {'ee': 'Belize', 'en': 'Belize'},
 'BJ': {'ee': 'Benin', 'en': 'Benin'},
 'BM': {'ee': 'Bermuda', 'en': 'Bermuda'},
 'BT': {'ee': 'Bhutan', 'en': 'Bhutan'},
 'MM': {'ee': 'Birma', 'en': 'Myanmar'},
 'BO': {'ee': 'Boliivia', 'en': 'Bolivia (Plurinational State of)'},
 'BQ': {'ee': 'Bonaire, Sint Eustatius ja Saba',
  'en': 'Bonaire, Sint Eustatius and Saba'},
 'BA': {'ee': 'Bosnia ja Hertsegoviina', 'en': 'Bosnia and Herzegovina'},
 'BW': {'ee': 'Botswana', 'en': 'Botswana'},
 'BV': {'ee': 'Bouvet', 'en': 'Bouvet Island'},
 'BR': {'ee': 'Brasiilia', 'en': 'Brazil'},
 'IO': {'ee': 'Briti India ookeani ala',
  'en': 'British Indian Ocean Territory'},
 'VG': {'ee': 'Briti Neitsisaared', 'en': 'Virgin Islands (British)'},
 'BN': {'ee': 'Brunei', 'en': 'Brunei Darussalam'},
 'BG': {'ee': 'Bulgaaria', 'en': 'Bulgaria'},
 'BF': {'ee': 'Burkina Faso', 'en': 'Burkina Faso'},
 'BI': {'ee': 'Burundi', 'en': 'Burundi'},
 'CO': {'ee': 'Colombia', 'en': 'Colombia'},
 'CK': {'ee': 'Cooki saared', 'en': 'Cook Islands'},
 'CR': {'ee': 'Costa Rica', 'en': 'Costa Rica'},
 'CW': {'ee': 'Curaçao', 'en': 'Curaçao'},
 'DJ': {'ee': 'Djibouti', 'en': 'Djibouti'},
 'DM': {'ee': 'Dominica', 'en': 'Dominica'},
 'DO': {'ee': 'Dominikaani Vabariik', 'en': 'Dominican Republic'},
 'EC': {'ee': 'Ecuador', 'en': 'Ecuador'},
 'EE': {'ee': 'Eesti', 'en': 'Estonia'},
 'EG': {'ee': 'Egiptus', 'en': 'Egypt'},
 'GQ': {'ee': 'Ekvatoriaal-Guinea', 'en': 'Equatorial Guinea'},
 'SV': {'ee': 'El Salvador', 'en': 'El Salvador'},
 'CI': {'ee': 'Elevandiluurannik', 'en': "Côte d'Ivoire"},
 'ER': {'ee': 'Eritrea', 'en': 'Eritrea'},
 'ET': {'ee': 'Etioopia', 'en': 'Ethiopia'},
 'FK': {'ee': 'Falklandi saared', 'en': 'Falkland Islands (Malvinas)'},
 'FJ': {'ee': 'Fidži', 'en': 'Fiji'},
 'FO': {'ee': 'Fääri saared', 'en': 'Faroe Islands'},
 'GA': {'ee': 'Gabon', 'en': 'Gabon'},
 'GM': {'ee': 'Gambia', 'en': 'Gambia'},
 'GH': {'ee': 'Ghana', 'en': 'Ghana'},
 'GI': {'ee': 'Gibraltar', 'en': 'Gibraltar'},
 'GD': {'ee': 'Grenada', 'en': 'Grenada'},
 'GE': {'ee': 'Gruusia', 'en': 'Georgia'},
 'GL': {'ee': 'Gröönimaa', 'en': 'Greenland'},
 'GP': {'ee': 'Guadeloupe', 'en': 'Guadeloupe'},
 'GU': {'ee': 'Guam', 'en': 'Guam'},
 'GT': {'ee': 'Guatemala', 'en': 'Guatemala'},
 'GG': {'ee': 'Guernsey', 'en': 'Guernsey'},
 'GN': {'ee': 'Guinea', 'en': 'Guinea'},
 'GW': {'ee': 'Guinea-Bissau', 'en': 'Guinea-Bissau'},
 'GY': {'ee': 'Guyana', 'en': 'Guyana'},
 'PH': {'ee': 'Filipiinid', 'en': 'Philippines'},
 'HT': {'ee': 'Haiti', 'en': 'Haiti'},
 'HM': {'ee': 'Heard ja McDonald', 'en': 'Heard Island and McDonald Islands'},
 'CN': {'ee': 'Hiina', 'en': 'China'},
 'ES': {'ee': 'Hispaania', 'en': 'Spain'},
 'NL': {'ee': 'Holland', 'en': 'Netherlands'},
 'HN': {'ee': 'Honduras', 'en': 'Honduras'},
 'HK': {'ee': 'Hongkong', 'en': 'Hong Kong'},
 'HR': {'ee': 'Horvaatia', 'en': 'Croatia'},
 'IE': {'ee': 'Iirimaa', 'en': 'Ireland'},
 'IL': {'ee': 'Iisrael', 'en': 'Israel'},
 'TL': {'ee': 'Ida-Timor', 'en': 'Timor-Leste'},
 'IN': {'ee': 'India', 'en': 'India'},
 'ID': {'ee': 'Indoneesia', 'en': 'Indonesia'},
 'IS': {'ee': 'Island', 'en': 'Iceland'},
 'IQ': {'ee': 'Iraak', 'en': 'Iraq'},
 'IR': {'ee': 'Iraan', 'en': 'Iran (Islamic Republic of)'},
 'IT': {'ee': 'Itaalia', 'en': 'Italy'},
 'JP': {'ee': 'Jaapan', 'en': 'Japan'},
 'JM': {'ee': 'Jamaica', 'en': 'Jamaica'},
 'YE': {'ee': 'Jeemen', 'en': 'Yemen'},
 'JE': {'ee': 'Jersey', 'en': 'Jersey'},
 'JO': {'ee': 'Jordaania', 'en': 'Jordan'},
 'CX': {'ee': 'Jõulusaar', 'en': 'Christmas Island'},
 'KY': {'ee': 'Kaimanisaared', 'en': 'Cayman Islands'},
 'KH': {'ee': 'Kambodža', 'en': 'Cambodia'},
 'CM': {'ee': 'Kamerun', 'en': 'Cameroon'},
 'CA': {'ee': 'Kanada', 'en': 'Canada'},
 'KZ': {'ee': 'Kasahstan', 'en': 'Kazakhstan'},
 'QA': {'ee': 'Katar', 'en': 'Qatar'},
 'KE': {'ee': 'Keenia', 'en': 'Kenya'},
 'CF': {'ee': 'Kesk-Aafrika Vabariik', 'en': 'Central African Republic'},
 'KI': {'ee': 'Kiribati', 'en': 'Kiribati'},
 'KM': {'ee': 'Komoorid', 'en': 'Comoros'},
 'CD': {'ee': 'Kongo Demokraatlik Vabariik',
  'en': 'Congo, Democratic Republic of the'},
 'CG': {'ee': 'Kongo Vabariik', 'en': 'Congo'},
 'CC': {'ee': 'Kookossaared', 'en': 'Cocos (Keeling) Islands'},
 'GR': {'ee': 'Kreeka', 'en': 'Greece'},
 'CU': {'ee': 'Kuuba', 'en': 'Cuba'},
 'KW': {'ee': 'Kuveit', 'en': 'Kuwait'},
 'CY': {'ee': 'Küpros', 'en': 'Cyprus'},
 'KG': {'ee': 'Kõrgõzstan', 'en': 'Kyrgyzstan'},
 'LA': {'ee': 'Laos', 'en': "Lao People's Democratic Republic"},
 'LT': {'ee': 'Leedu', 'en': 'Lithuania'},
 'LS': {'ee': 'Lesotho', 'en': 'Lesotho'},
 'LB': {'ee': 'Liibanon', 'en': 'Lebanon'},
 'LR': {'ee': 'Libeeria', 'en': 'Liberia'},
 'LI': {'ee': 'Liechtenstein', 'en': 'Liechtenstein'},
 'LY': {'ee': 'Liibüa', 'en': 'Libya'},
 'LU': {'ee': 'Luksemburg', 'en': 'Luxembourg'},
 'ZA': {'ee': 'Lõuna-Aafrika Vabariik', 'en': 'South Africa'},
 'GS': {'ee': 'Lõuna-Georgia ja Lõuna-Sandwichi saared',
  'en': 'South Georgia and the South Sandwich Islands'},
 'KR': {'ee': 'Lõuna-Korea', 'en': 'Korea, Republic of'},
 'SS': {'ee': 'Lõuna-Sudaan', 'en': 'South Sudan'},
 'EH': {'ee': 'Lääne-Sahara', 'en': 'Western Sahara'},
 'LV': {'ee': 'Läti', 'en': 'Latvia'},
 'MO': {'ee': 'Macau', 'en': 'Macao'},
 'MG': {'ee': 'Madagaskar', 'en': 'Madagascar'},
 'MY': {'ee': 'Malaisia', 'en': 'Malaysia'},
 'MW': {'ee': 'Malawi', 'en': 'Malawi'},
 'MV': {'ee': 'Maldiivid', 'en': 'Maldives'},
 'ML': {'ee': 'Mali', 'en': 'Mali'},
 'MT': {'ee': 'Malta', 'en': 'Malta'},
 'IM': {'ee': 'Man', 'en': 'Isle of Man'},
 'MA': {'ee': 'Maroko', 'en': 'Morocco'},
 'MH': {'ee': 'Marshalli Saared', 'en': 'Marshall Islands'},
 'MQ': {'ee': 'Martinique', 'en': 'Martinique'},
 'MR': {'ee': 'Mauritaania', 'en': 'Mauritania'},
 'MU': {'ee': 'Mauritius', 'en': 'Mauritius'},
 'YT': {'ee': 'Mayotte', 'en': 'Mayotte'},
 'MX': {'ee': 'Mehhiko', 'en': 'Mexico'},
 'FM': {'ee': 'Mikroneesia Liiduriigid',
  'en': 'Micronesia (Federated States of)'},
 'MD': {'ee': 'Moldova', 'en': 'Moldova, Republic of'},
 'MC': {'ee': 'Monaco', 'en': 'Monaco'},
 'MN': {'ee': 'Mongoolia', 'en': 'Mongolia'},
 'ME': {'ee': 'Montenegro', 'en': 'Montenegro'},
 'MS': {'ee': 'Montserrat', 'en': 'Montserrat'},
 'MZ': {'ee': 'Mosambiik', 'en': 'Mozambique'},
 'NA': {'ee': 'Namiibia', 'en': 'Namibia'},
 'NR': {'ee': 'Nauru', 'en': 'Nauru'},
 'NP': {'ee': 'Nepal', 'en': 'Nepal'},
 'NI': {'ee': 'Nicaragua', 'en': 'Nicaragua'},
 'NG': {'ee': 'Nigeeria', 'en': 'Nigeria'},
 'NE': {'ee': 'Niger', 'en': 'Niger'},
 'NU': {'ee': 'Niue', 'en': 'Niue'},
 'NF': {'ee': 'Norfolk', 'en': 'Norfolk Island'},
 'NO': {'ee': 'Norra', 'en': 'Norway'},
 'OM': {'ee': 'Omaan', 'en': 'Oman'},
 'PG': {'ee': 'Paapua Uus-Guinea', 'en': 'Papua New Guinea'},
 'PK': {'ee': 'Pakistan', 'en': 'Pakistan'},
 'PS': {'ee': 'Palestiina', 'en': 'Palestine, State of'},
 'PA': {'ee': 'Panama', 'en': 'Panama'},
 'PY': {'ee': 'Paraguay', 'en': 'Paraguay'},
 'PE': {'ee': 'Peruu', 'en': 'Peru'},
 'PN': {'ee': 'Pitcairn', 'en': 'Pitcairn'},
 'PL': {'ee': 'Poola', 'en': 'Poland'},
 'PT': {'ee': 'Portugal', 'en': 'Portugal'},
 'GF': {'ee': 'Prantsuse Guajaana', 'en': 'French Guiana'},
 'TF': {'ee': 'Prantsuse Lõunaalad', 'en': 'French Southern Territories'},
 'PF': {'ee': 'Prantsuse Polüneesia', 'en': 'French Polynesia'},
 'FR': {'ee': 'Prantsusmaa', 'en': 'France'},
 'PR': {'ee': 'Puerto Rico', 'en': 'Puerto Rico'},
 'KP': {'ee': 'Põhja-Korea', 'en': "Korea (Democratic People's Republic of)"},
 'MK': {'ee': 'Põhja-Makedoonia', 'en': 'North Macedonia'},
 'MP': {'ee': 'Põhja-Mariaanid', 'en': 'Northern Mariana Islands'},
 'RE': {'ee': 'Réunion', 'en': 'Réunion'},
 'CV': {'ee': 'Roheneemesaared', 'en': 'Cabo Verde'},
 'SE': {'ee': 'Rootsi', 'en': 'Sweden'},
 'RO': {'ee': 'Rumeenia', 'en': 'Romania'},
 'RW': {'ee': 'Rwanda', 'en': 'Rwanda'},
 'SB': {'ee': 'Saalomoni Saared', 'en': 'Solomon Islands'},
 'BL': {'ee': 'Saint-Barthélemy', 'en': 'Saint Barthélemy'},
 'SH': {'ee': 'Saint Helena',
  'en': 'Saint Helena, Ascension and Tristan da Cunha'},
 'KN': {'ee': 'Saint Kitts ja Nevis', 'en': 'Saint Kitts and Nevis'},
 'LC': {'ee': 'Saint Lucia', 'en': 'Saint Lucia'},
 'MF': {'ee': 'Saint-Martin', 'en': 'Saint Martin (French part)'},
 'PM': {'ee': 'Saint-Pierre ja Miquelon', 'en': 'Saint Pierre and Miquelon'},
 'VC': {'ee': 'Saint Vincent ja Grenadiinid',
  'en': 'Saint Vincent and the Grenadines'},
 'DE': {'ee': 'Saksamaa', 'en': 'Germany'},
 'ZM': {'ee': 'Sambia', 'en': 'Zambia'},
 'WS': {'ee': 'Samoa', 'en': 'Samoa'},
 'SM': {'ee': 'San Marino', 'en': 'San Marino'},
 'ST': {'ee': 'São Tomé ja Príncipe', 'en': 'Sao Tome and Principe'},
 'SA': {'ee': 'Saudi Araabia', 'en': 'Saudi Arabia'},
 'SC': {'ee': 'Seišellid', 'en': 'Seychelles'},
 'SN': {'ee': 'Senegal', 'en': 'Senegal'},
 'RS': {'ee': 'Serbia', 'en': 'Serbia'},
 'SL': {'ee': 'Sierra Leone', 'en': 'Sierra Leone'},
 'SG': {'ee': 'Singapur', 'en': 'Singapore'},
 'SX': {'ee': 'Sint Maarten', 'en': 'Sint Maarten (Dutch part)'},
 'SK': {'ee': 'Slovakkia', 'en': 'Slovakia'},
 'SI': {'ee': 'Sloveenia', 'en': 'Slovenia'},
 'SO': {'ee': 'Somaalia', 'en': 'Somalia'},
 'FI': {'ee': 'Soome', 'en': 'Finland'},
 'LK': {'ee': 'Sri Lanka', 'en': 'Sri Lanka'},
 'SD': {'ee': 'Sudaan', 'en': 'Sudan'},
 'SR': {'ee': 'Suriname', 'en': 'Suriname'},
 'GB': {'ee': 'Suurbritannia',
  'en': 'United Kingdom of Great Britain and Northern Ireland'},
 'SZ': {'ee': 'Svaasimaa', 'en': 'Eswatini'},
 'SJ': {'ee': 'Svalbard ja Jan Mayen', 'en': 'Svalbard and Jan Mayen'},
 'SY': {'ee': 'Süüria', 'en': 'Syrian Arab Republic'},
 'CH': {'ee': 'Šveits', 'en': 'Switzerland'},
 'ZW': {'ee': 'Zimbabwe', 'en': 'Zimbabwe'},
 'DK': {'ee': 'Taani', 'en': 'Denmark'},
 'TJ': {'ee': 'Tadžikistan', 'en': 'Tajikistan'},
 'TH': {'ee': 'Tai', 'en': 'Thailand'},
 'TW': {'ee': 'Taiwan', 'en': 'Taiwan, Province of China'},
 'TZ': {'ee': 'Tansaania', 'en': 'Tanzania, United Republic of'},
 'TG': {'ee': 'Togo', 'en': 'Togo'},
 'TK': {'ee': 'Tokelau', 'en': 'Tokelau'},
 'TO': {'ee': 'Tonga', 'en': 'Tonga'},
 'TT': {'ee': 'Trinidad ja Tobago', 'en': 'Trinidad and Tobago'},
 'TD': {'ee': 'Tšaad', 'en': 'Chad'},
 'CZ': {'ee': 'Tšehhi', 'en': 'Czechia'},
 'CL': {'ee': 'Tšiili', 'en': 'Chile'},
 'TN': {'ee': 'Tuneesia', 'en': 'Tunisia'},
 'TR': {'ee': 'Türgi', 'en': 'Turkey'},
 'TM': {'ee': 'Türkmenistan', 'en': 'Turkmenistan'},
 'TC': {'ee': 'Turks ja Caicos', 'en': 'Turks and Caicos Islands'},
 'TV': {'ee': 'Tuvalu', 'en': 'Tuvalu'},
 'UG': {'ee': 'Uganda', 'en': 'Uganda'},
 'UA': {'ee': 'Ukraina', 'en': 'Ukraine'},
 'HU': {'ee': 'Ungari', 'en': 'Hungary'},
 'UY': {'ee': 'Uruguay', 'en': 'Uruguay'},
 'VI': {'ee': 'USA Neitsisaared', 'en': 'Virgin Islands (U.S.)'},
 'UZ': {'ee': 'Usbekistan', 'en': 'Uzbekistan'},
 'NC': {'ee': 'Uus-Kaledoonia', 'en': 'New Caledonia'},
 'NZ': {'ee': 'Uus-Meremaa', 'en': 'New Zealand'},
 'BY': {'ee': 'Valgevene', 'en': 'Belarus'},
 'VU': {'ee': 'Vanuatu', 'en': 'Vanuatu'},
 'VA': {'ee': 'Vatikan', 'en': 'Holy See'},
 'RU': {'ee': 'Venemaa', 'en': 'Russian Federation'},
 'VE': {'ee': 'Venezuela', 'en': 'Venezuela (Bolivarian Republic of)'},
 'VN': {'ee': 'Vietnam', 'en': 'Viet Nam'},
 'WF': {'ee': 'Wallis ja Futuna', 'en': 'Wallis and Futuna'},
 'UM': {'ee': 'Ühendriikide hajasaared',
  'en': 'United States Minor Outlying Islands'}}

a2_dct['UK'] = {'ee': 'Ühendkuningriik', 'en': 'United Kingdom'}